const posts = [
  {
    albumId: 1,
    id: 1,
    title: "Humans Behaviour",
    url: "https://picsum.photos/seed/picsum/200/300",
    thumbnailUrl: " https://picsum.photos/200/300/?blur",
    discription: "Aqsa choudhary  ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 2,
    title: "Software Engineering",
    url: "https://picsum.photos/200/300",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Sonobia choudharY ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 3,
    title: "Information Technolog",
    url: "https://picsum.photos/id/870/200/300?grayscale&blur=2",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Sohail Waraich  ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 4,
    title: "Computer Sciences",
    url: "https://picsum.photos/seed/picsum/200/300",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: " Faizan  ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 5,
    title: "SoftWare Engineer",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Muhammad Aslam",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 6,
    title: "Hotti Culture",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Balquees Akhtar  ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 7,
    title: "Cooking Vlog",
    url: "https://picsum.photos/200/300.jpg",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Muhammad Tanveer  ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 8,
    title: "Makeup Tutorial",
    url: "https://picsum.photos/200/300.webp",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Sherish  Muneer",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 9,
    title: "Dress Collection",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Tahreem ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 10,
    title: "Brands",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Iqra ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 11,
    title: "Phone Collection",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Huma",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 12,
    title: "HR",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Madeeha ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 13,
    title: "Cricket Club",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: " Adnan Sohail ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 14,
    title: " polo club",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: " vIKY gOSPAL ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 15,
    title: "Makeup Collection",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: " Sidra",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 16,
    title: "jULLREY cOLLECTION",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Aqsachoudhary  ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 17,
    title: "Coading",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "hhttps://picsum.photos/200/300/?blur",
    discription: "Faizan ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 18,
    title: "Coading Lover",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Tahreem ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 19,
    title: "Phone Product",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Atif ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 20,
    title: "Books Collection",
    url: "https://picsum.photos/200/300?grayscale",
    thumbnailUrl: "https://picsum.photos/200/300/?blur",
    discription: "Sharjeel ",
    Time: "10:50AM",
    Likes: "(67)",
    share: "(53)",
  },
];

export default posts;
