const ProductsData = [
  {
    id: 1,
    name: "iPhone 5s",
    company: "iPhone",
    quantity: 9,
    price: 100000,
    moodal: "SS#45",
  },
  {
    id: 2,
    name: "iPhone 5",
    company: "iPhone",
    quantity: 5,
    price: 4566,
    moodal: "SS#45",
  },
  {
    id: 3,
    name: "iPhone 8x",
    company: "iPhone",
    quantity: 5,
    price: 7890,
    moodal: "SS#45",
  },
  {
    id: 4,
    name: "iPhone x",
    company: "iPhone",
    quantity: 9,
    price: 888893,
    moodal: "SS#45",
  },
  {
    id: 5,
    name: "iPhone 8",
    company: "iPhone",
    quantity: 10,
    price: 40903,
    moodal: "SS#45",
  },
  {
    id: 6,
    name: "iPhone promax",
    company: "iPhone",
    quantity: 13,
    price: 40930000,
    moodal: "SS#45",
  },
  {
    id: 7,
    name: "iPhone 6",
    company: "iPhone",
    quantity: 12,
    price: 4093,
    moodal: "SS#45",
  },
  {
    id: 8,
    name: "iphonse 6s",
    company: "iphone",
    quantity: 15,
    price: 25000,
    moodal: "ss#46",
  },

  {
    id: 9,
    name: "iPhone 7",
    company: "iPhone",
    quantity: 18,
    price: 5093,
    moodal: "SS#49",
  },
  {
    id: 10,
    name: "iPhone 7s",
    company: "iPhone",
    quantity: 19,
    price: 89993,
    moodal: "SS#85",
  },
];

export default ProductsData;
